services:
  survey-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    environment:
      - NEXT_PUBLIC_API_URL
      - NEXT_PUBLIC_SOCKET_URL
    expose:
      - "3003"
    container_name: survey-app
    networks:
      - network-survey-app

  survey-app-nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: survey-app-nginx
    ports:
      - "3003:80"
    depends_on:
      - survey-app
    networks:
      - network-survey-app

networks:
  network-survey-app:
    external: true