import localFont from "next/font/local";
import "./globals.css";
import ProviderWrapper from "./providers";

const anuphanLight = localFont({
  src: './fonts/Anuphan-Light.ttf',
  variable: '--font-anuphan-light',
  display: 'swap',
});

const anuphanSemiBold = localFont({
  src: './fonts/Anuphan-SemiBold.ttf',
  variable: '--font-anuphan-semibold',
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${anuphanLight.variable} ${anuphanSemiBold.variable}`}>
        <ProviderWrapper>{children}</ProviderWrapper>
      </body>
    </html>
  );
}
